[package]
name = "pop-system-updater-gtk"
version = "0.1.0"
edition = "2018"
license = "MPL-2.0"

[dependencies]
cascade = "1.0.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3.17"
gio = "0.14.8"
glib = "0.14.8"
gtk = "0.14.3"
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.0"
once_cell = "1.8.0"
pop-system-updater = { path = "../" }
postage = "0.4.1"
ron = "0.7.0"
rust-embed = "6.2.0"
smol = "1.2.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zbus = "2.0.0"

[features]
